<a href="https://colab.research.google.com/github/BrunaSR/MinicursoPython/blob/main/Notebooks/Aula/ParteIV_Aula.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Minicurso Python Parte IV

Esse notebook apresenta exemplos e exercícios sobre a biblioteca Numpy

# Como criar um array

In [35]:
# Importação da biblioteca
import numpy as np

### Vetores

In [2]:
# Criação de um vetor a partir de uma lista

Meu primeiro array com numpy =  [1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
# Informações de um array

Quantidade de elementos =  5
Shape =  (5,)
Dimensões =  1
Tipos de dados do vetor =  int64


In [3]:
# Acesso aos elementos de um array unidimensional

O segundo elemento do meu vetor é =  2
Os 3 últimos elementos são =  [3 4 5]
O segundo terceiro e quarto elementos são =  [2 3]


### Matrizes

In [49]:
# Criação de uma matriz a partir de uma lista de listas

Minha matriz = 
 [[1 2]
 [3 4]]
Shape =  (2, 2)


In [6]:
# Acesso aos elementos de um array multidimensional

Primeira linha da matriz =  [1 2]
Primeiro elemento da primeira linha =  1
Primeiro elemento da segunda linha =  3


### Alterando elementos


In [7]:
# Alterar o elemento de um array
# Exemplo vetor

# Exemplo matriz

Vetor original =  [1 2 3 4 5]
Primeiro elemento alterado =  [10  2  3  4  5]
Matriz original = 
 [[1 2]
 [3 4]]
Último elemento da segunda linha da matriz alterado =  [[ 1  2]
 [ 3 40]]


### Funções para criação de arrays

In [8]:
# Matriz 3x4 vazia

[[4.64267167e-310 4.64267285e-310 3.95252517e-323 4.64267285e-310]
 [3.95252517e-323 4.64267285e-310 4.44659081e-323 0.00000000e+000]
 [4.64267285e-310 4.64267285e-310 4.64267285e-310 0.00000000e+000]]


In [9]:
# Vetor coluna com zeros

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [10]:
# Vetor linha de valor 1

[[1. 1. 1. 1. 1. 1.]]


In [11]:
# Vetor com valores igualmente espaçados dentro de um intervalo

[0.         0.07142857 0.14285714 0.21428571 0.28571429 0.35714286
 0.42857143 0.5        0.57142857 0.64285714 0.71428571 0.78571429
 0.85714286 0.92857143 1.        ]


In [12]:
# Vetor com valores dentro de um intervalo com passo igual 2

Pares de 1 a 10 =  [ 2  4  6  8 10]


### Variáveis aleatórias

In [13]:
# Valores aleatórios de uma distribuição uniforme dentro do intervalo [0,1)

[0.30974661 0.99522831 0.58435177 0.43609707 0.16183526 0.66676003
 0.51639393 0.09818761 0.47328499 0.37730236]


In [36]:
# Valores aleatórios inteiros de uma distribuição uniforme dentro do intervalo 

[[1 1 3]
 [4 0 1]]


In [15]:
# Valores aleatórios de uma distribuição normal padrão 

[[ 0.09143957  0.28975565 -1.30899325]
 [ 0.14526942 -1.09427728 -1.05974819]]


### Operações com os arrays

In [16]:
# Operações entre um número e uma array

Soma = 
 [[3 4 5]
 [6 7 8]]

Subtração = 
 [[-1  0  1]
 [ 2  3  4]]

Divisão = 
 [[0.5 1.  1.5]
 [2.  2.5 3. ]]

Multiplicação = 
 [[ 2  4  6]
 [ 8 10 12]]


In [17]:
# Operações com matrizes

Matriz 1 = 
 [[2 3]
 [1 5]]

Matriz 2 = 
 [[4. 4.]
 [4. 4.]]

Multiplicação elemento por elemento de duas matrizes = 
 [[ 8. 12.]
 [ 4. 20.]]

Multiplicação matricial = 
 [[20. 20.]
 [24. 24.]]

Multiplicação matricial = 
 [[20. 20.]
 [24. 24.]]


In [46]:
# Matriz transposta

Matriz, transposta = 
 [[2 1]
 [3 5]]


In [47]:
# Cálculo da matriz inversa

Matriz inversa = 
 [[ 0.71428571 -0.42857143]
 [-0.14285714  0.28571429]]


### Funções importantes

In [20]:
# Redimensionar um array
vetor = [True, False, False, True, True, False]

Array original =  [ True False False  True  True  True]
Array modificado = 
 [[ True False]
 [False  True]
 [ True  True]]


In [21]:
# Copiar um array

# Modificando vetor 2

# Verificando o vetor original

# Utilizando np.copy()
print('\n' + '-'*20 + 'Utilizando np.copy()' + '-'*20)

# Modificando vetor 3

# Verificando o vetor original

Vetor 1 =  [[1. 1. 1. 1. 1. 1.]]

Vetor 2 =  [1. 1. 1.]

Vetor 2 modificado =  [5. 1. 1.]

Verificando o vetor original =  [[5. 1. 1. 1. 1. 1.]]

--------------------Utilizando np.copy()--------------------

Vetor 3 =  [5. 1. 1.]

Vetor 3 modificado =  [ 5.  1. 33.]

Verificando o vetor original =  [[5. 1. 1. 1. 1. 1.]]


In [22]:
# Soma de elementos

Soma das colunas =  [5 7 9]
Soma das linhas =  [ 6 15]
Soma de todos os elementos =  21


In [23]:
# Algumas estatísticas


Desvio padrão =  1.707825127659933
Média =  3.5
Variância =  2.9166666666666665


In [24]:
# Concatenação de vetores
x1 = np.arange(0, 10, 2).reshape((-1, 1))
x2 = np.arange(1, 11, 2).reshape((-1, 1))

# Juntando as colunas
#x3 = np.c_[x1, x2]


# Concatenação por linhas


x1 = 
 [[0]
 [2]
 [4]
 [6]
 [8]]
x2 = 
 [[1]
 [3]
 [5]
 [7]
 [9]]
Concatenando coluna = 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Concatenando linhas = 
 [[0]
 [2]
 [4]
 [6]
 [8]
 [1]
 [3]
 [5]
 [7]
 [9]]


# Exercícios

## Exercício 1

Crie um array de inteiros de 32 bits de formato (4, 5, 3), onde todos os elementos são iguais a 7.


In [25]:
# Escreva sua solução aqui.

### Solução

In [26]:
n = np.ones((4, 5, 3), dtype=np.int32)*7
print("Array = \n", n)
print("\nTipos de dados do array = ", n.dtype)

Array = 
 [[[7 7 7]
  [7 7 7]
  [7 7 7]
  [7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]
  [7 7 7]
  [7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]
  [7 7 7]
  [7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]
  [7 7 7]
  [7 7 7]
  [7 7 7]]]

Tipos de dados do array =  int32


## Exercício 2
Faça uma função que dado um intervalo fechado [a, b] e um número de pontos n, retorne o vetor x formado pelos n pontos obtidos a partir do intervalo, e o vetor y cujo i-ésimo elemento é dado por 

> $y_i = x_i^2 + 5$.




In [27]:
# Escreva sua solução aqui.

### Solução

In [28]:
a = 0
b = 9
n = 10
x = np.linspace(a, b, n)
y = x**2 + 5

print('x = ', x)
print('\ny = ', y)

x =  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

y =  [ 5.  6.  9. 14. 21. 30. 41. 54. 69. 86.]


## Exercício 3
Uma pista de Kart permite 10 voltas para cada um de 6 corredores. Uma matriz com os tempos (em segundos) de cada volta de cada corredor é dada. Com essa matriz, seu programa deve informar:
 - De quem foi a melhor volta da prova, e em que volta.
 - Qual foi o tempo médio de cada corredor.
 - Classificação final em ordem crescente com base no tempo médio.

**OBS:** Não se esqueça de executar a célula seguinte para definir a matriz.

In [29]:
# Matriz com o tempo dos corredores em cada volta
# As linhas da matriz se referam ao corredor e as colunas, ao tempo de cada volta
np.random.seed(1)
m_tempo = np.random.randint(60, 180, size=(6, 10))
print(m_tempo)

[[ 97 167  72 132  69 135  65 139 124  76]
 [ 61 136 131 169  66  85 110  80 161  78]
 [144  71 166  88  89  74 110 128 147 147]
 [165 173 179 154 156 146  73 165  69  67]
 [123 121  82 117  61  60 120 141  68 148]
 [ 73 175 107 166 132  90 131  63 130  81]]


In [30]:
# Escreva sua solução aqui.

### Solução

In [31]:
# Volta com menor tempo
menor_tempo = np.min(m_tempo)

# Index da melhor volta
id_menor_tempo = np.where(m_tempo == menor_tempo)

# Mostrando o resultado
print("O melhor tempo foi na {}ª volta do corredor {}.".format(id_menor_tempo[1][0], id_menor_tempo[0][0]))

O melhor tempo foi na 5ª volta do corredor 4.


In [32]:
# Tempo médio
media = np.mean(m_tempo, axis=1)
print('Média de cada corredor = \n', media)

Média de cada corredor = 
 [107.6 107.7 116.4 134.7 104.1 114.8]


In [33]:
# Classificação
classificacao = np.argsort(media)
print("Classificação dos corredores(1º lugar até 6º) = ", classificacao)

Classificação dos corredores(1º lugar até 6º) =  [4 0 1 5 2 3]
