<a href="https://colab.research.google.com/github/BrunaSR/MinicursoPython/blob/main/Notebooks/ParteIV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Minicurso Python Parte IV

Esse notebook apresenta exemplos e exercícios sobre a biblioteca Numpy

# Como criar um array

In [1]:
# Importação da biblioteca
import numpy as np

### Vetores

In [ ]:
# Criação de um vetor a partir de uma lista
vetor = np.array([1, 2, 3, 4, 5])

print("Meu primeiro array com numpy = ", vetor)
print(type(vetor))

Meu primeiro array com numpy =  [1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# Acesso aos elementos de um array unidimensional
print('O segundo elemento do meu vetor é = ', vetor[1])
print('Os 3 últimos elementos são = ', vetor[-3:])
print('O segundo, terceiro e quarto elementos são = ', vetor[1:3])

O segundo elemento do meu vetor é =  2
Os 3 últimos elementos são =  [3 4 5]
O segundo terceiro e quarto elementos são =  [2 3]


In [ ]:
# Informações de um array
print('Quantidade de elementos = ', vetor.size)
print("Shape = ", vetor.shape)
print("Dimensões = ", vetor.ndim)
print("Tipos de dados do vetor = ", vetor.dtype)

Shape =  (5,)
Dimensões =  1
Tipos de dados do vetor =  int64


### Matrizes

In [ ]:
# Criação de uma matriz a partir de uma lista de listas
matriz = np.array([[1,2], [3, 4]])

print("Minha matriz quadrada = \n", matriz)
print("Shape = ", matriz.shape)

Minha matriz quadrada = 
 [[1 2]
 [3 4]]
Shape =  (2, 2)


In [ ]:
# Acesso aos elementos de um array multidimensional
print('Primeira linha da matriz = ', matriz[0])
print('Primeiro elemento da primeira linha = ', matriz[0, 0])
print('Primeiro elemento da segunda linha = ', matriz[1, 0])

Primeira linha da matriz =  [1 2]
Primeiro elemento da primeira linha =  1
Primeiro elemento da segunda linha =  3


### Alterando elementos


In [ ]:
# Alterar o elemento de um array
print("Vetor original = ", vetor)
vetor[0] = 10
print("Primeiro elemento alterado = ", vetor)

print('Matriz original = \n', matriz)
matriz[1, 1] = 40
print('Último elemento da segunda linha da matriz alterado = ', matriz)

### Funções para criação de arrays

In [ ]:
# Matriz 3x4 vazia
vazia = np.empty((3, 4))
print(vazia)

[[4.66095604e-310 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.04082753e-047 4.96012452e-090 2.95881656e-032]
 [1.55075274e+184 4.66239379e-033 3.99910963e+252 1.46030983e-319]]


In [ ]:
# Vetor coluna com zeros
zeros = np.zeros((6, 1))
print(zeros)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [ ]:
# Vetor linha de valor 1
vetor_um = np.ones((1, 6))
print(vetor_um)

[[1. 1. 1. 1. 1. 1.]]


In [ ]:
# Vetor com valores igualmente espaçados dentro de um intervalo
vetor = np.linspace(0, 1, 15)
print(vetor)

[0.         0.07142857 0.14285714 0.21428571 0.28571429 0.35714286
 0.42857143 0.5        0.57142857 0.64285714 0.71428571 0.78571429
 0.85714286 0.92857143 1.        ]


In [ ]:
# Vetor com valores dentro de um intervalo com passo igual 2
pares = np.arange(2, 11, 2)
print('Pares de 1 a 10 = ', pares)

Pares de 1 a 10 =  [ 2  4  6  8 10]


### Variáveis aleatórias

In [ ]:
# Valores aleatórios de uma distribuição uniforme dentro do intervalo [0,1)
v = np.random.random(10)
print(v)

[0.51093677 0.88386357 0.96047983 0.98696519 0.63858842 0.83554216
 0.98273158 0.28953125 0.73679483 0.105234  ]


In [ ]:
# Valores aleatórios inteiros de uma distribuição uniforme dentro do intervalo 
inteiros = np.random.randint(7, size=(2, 3))
print(inteiros)

1


In [ ]:
# Valores aleatórios de uma distribuição normal padrão 
v = np.random.randn(2, 3)
print(v)

[[ 1.40974587  1.28016672 -0.5136921 ]
 [ 0.07090824 -0.23663137  0.01907614]]


### Operações com os arrays

In [ ]:
# Operações entre um número e uma array
matriz = np.array([[1, 2, 3], [4, 5, 6]])
num = 2

print('Soma = \n', matriz + num)
print('\nSubtração = \n', matriz - num)
print('\nDivisão = \n', matriz / num)
print('\nMultiplicação = \n', matriz * num)

Soma = 
 [[3 4 5]
 [6 7 8]]

Subtração = 
 [[-1  0  1]
 [ 2  3  4]]

Divisão = 
 [[0.5 1.  1.5]
 [2.  2.5 3. ]]

Multiplicação = 
 [[ 2  4  6]
 [ 8 10 12]]


In [ ]:
# Operações com matrizes
matriz1 = np.array([[2, 3], [1, 5]])
matriz2 = 4*np.ones((2, 2))

print('Matriz 1 = \n', matriz1)
print('\nMatriz 2 = \n', matriz2)

print('\nMultiplicação elemento por elemento de duas matrizes = \n', matriz1 * matriz2)
print('\nMultiplicação matricial = \n', matriz1 @ matriz2)
print('\nMultiplicação matricial = \n', matriz1.dot(matriz2))

Matriz 1 = 
 [[2 3]
 [1 5]]

Matriz 2 = 
 [[4. 4.]
 [4. 4.]]

Multiplicação entre os elemento por elemento de duas matrizes = 
 [[ 8. 12.]
 [ 4. 20.]]

Multiplicação matricial = 
 [[20. 20.]
 [24. 24.]]

Multiplicação matricial = 
 [[20. 20.]
 [24. 24.]]


In [12]:
# Matriz transposta
print('Matriz transposta =\n', np.transpose(matriz))

Matriz transposta =
 [[ 1.   3.   2. ]
 [ 0.  -1.  -1.5]
 [-2.   0.   3. ]]


In [11]:
# Cálculo da matriz inversa
matriz = np.array([[1, 0, -2], [3, -1, 0], [2, -1.5, 3]])
print("Matriz =\n", matriz)
print("\nMatriz inversa =\n", np.linalg.inv(matriz))

Matriz 2 =
 [[ 1.   0.  -2. ]
 [ 3.  -1.   0. ]
 [ 2.  -1.5  3. ]]

Matriz inversa =
 [[-1.5   1.5  -1.  ]
 [-4.5   3.5  -3.  ]
 [-1.25  0.75 -0.5 ]]


### Funções importantes

In [ ]:
# Redimensionar um array
vetor = np.array([True, False, False, True, True, True])
matriz = vetor.reshape((3,2))

print("Array original = ", vetor)
print("Array modificado = \n", matriz)

Array original =  [ True False False  True  True  True]
Array modificado = 
 [[ True False]
 [False  True]
 [ True  True]]


In [ ]:
# Copiar um array
vetor1 = np.ones((1, 6))
print('Vetor 1 = ', vetor1)

vetor2 = vetor1[0, :3]
print('\nVetor 2 = ', vetor2)

# Modificando vetor 2
vetor2[0] = 5
print('\nVetor 2 modificado = ', vetor2)

# Verificando o vetor original
print('\nVerificando o vetor original = ', vetor1)

# Utilizando np.copy()
print('\n' + '-'*20 + 'Utilizando np.copy()' + '-'*20)
vetor3 = np.copy(vetor1[0, :3])
print('\nVetor 3 = ', vetor3)

vetor3[2] = 33
print("\nVetor 3 modificado = ", vetor3)

print("\nVerificando o vetor original = ", vetor1)

Vetor 1 =  [[1. 1. 1. 1. 1. 1.]]

Vetor 2 =  [1. 1. 1.]

Vetor 2 modificado =  [5. 1. 1.]

Verificando o vetor original =  [[5. 1. 1. 1. 1. 1.]]

--------------------Utilizando np.copy()--------------------

Vetor 3 =  [5. 1. 1.]

Vetor 3 modificado =  [ 5.  1. 33.]

Verificando o vetor original =  [[5. 1. 1. 1. 1. 1.]]


In [ ]:
# Soma de elementos
matriz = np.array([[1, 2, 3], [4, 5, 6]])

print('Soma das colunas = ', np.sum(matriz, axis=0))
print('Soma das linhas = ', np.sum(matriz, axis=1))
print('Soma de todos os elementos = ', np.sum(matriz))

Soma das colunas =  [5 7 9]
Soma das linhas =  [ 6 15]
Soma de todos os elementos =  21


In [ ]:
# Algumas estatísticas

print('Desvio padrão = ', np.std(matriz))
print('Média = ', np.mean(matriz))
print('Variância = ', np.var(matriz))

Desvio padrão =  1.707825127659933
Média =  3.5
Variância =  2.9166666666666665


In [9]:
# Concatenação de vetores
x1 = np.arange(0, 10, 2).reshape(-1, 1)
x2 = np.arange(1, 11, 2).reshape(-1, 1)
print('x1 = \n', x1)
print('x2 = \n', x2)

# Juntando as colunas
#x3 = np.c_[x1, x2]
x3 = np.concatenate((x1, x2), axis=1)
print('Concatenando coluna = \n', x3)

# Concatenação por linhas
x4 = np.concatenate((x1, x2), axis=0)
print('Concatenando linhas = \n', x4)

x1 = 
 [[0]
 [2]
 [4]
 [6]
 [8]]
x2 = 
 [[1]
 [3]
 [5]
 [7]
 [9]]
Concatenando coluna = 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Concatenando linhas = 
 [[0]
 [2]
 [4]
 [6]
 [8]
 [1]
 [3]
 [5]
 [7]
 [9]]


# Exercícios

## Exercício 1

Crie um array de inteiros de 32 bits de formato (4, 5, 3), onde todos os elementos são iguais a 7.


In [ ]:
# Escreva sua solução aqui.

### Solução

In [ ]:
n = np.ones((4, 5, 3), dtype=np.int32)*7
print("Array = \n", n)
print("\nTipos de dados do array = ", n.dtype)

Array = 
 [[[7 7 7]
  [7 7 7]
  [7 7 7]
  [7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]
  [7 7 7]
  [7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]
  [7 7 7]
  [7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]
  [7 7 7]
  [7 7 7]
  [7 7 7]]]

Tipos de dados do array =  int32


## Exercício 2
Faça uma função que dado um intervalo fechado [a, b] e um número de pontos n, retorne o vetor x formado pelos n pontos obtidos a partir do intervalo, e o vetor y cujo i-ésimo elemento é dado por 

> $y_i = x_i^2 + 5$.




In [ ]:
# Escreva sua solução aqui.

### Solução

In [ ]:
a = 0
b = 9
n = 10
x = np.linspace(a, b, n)
y = x**2 + 5

print('x = ', x)
print('\ny = ', y)

x =  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

y =  [ 5.  6.  9. 14. 21. 30. 41. 54. 69. 86.]


### Exercício 3
Uma pista de Kart permite 10 voltas para cada um de 6 corredores. Uma matriz com os tempos (em segundos) de cada volta de cada corredor é dada. Com essa matriz, seu programa deve informar:
 - De quem foi a melhor volta da prova, e em que volta.
 - Qual foi o tempo médio de cada corredor.
 - Classificação final em ordem crescente com base no tempo médio.

**OBS:** Não se esqueça de executar a célula seguinte para definir a matriz.

In [ ]:
# Matriz com o tempo dos corredores em cada volta
# As linhas da matriz se referam ao corredor e as colunas, ao tempo de cada volta
np.random.seed(1)
m_tempo = np.random.randint(60, 180, size=(6, 10))
print(m_tempo)

[[ 97 167  72 132  69 135  65 139 124  76]
 [ 61 136 131 169  66  85 110  80 161  78]
 [144  71 166  88  89  74 110 128 147 147]
 [165 173 179 154 156 146  73 165  69  67]
 [123 121  82 117  61  60 120 141  68 148]
 [ 73 175 107 166 132  90 131  63 130  81]]


In [ ]:
# Escreva sua solução aqui.

### Solução

In [ ]:
# Volta com menor tempo
menor_tempo = np.min(m_tempo)

# Index da melhor volta
id_menor_tempo = np.where(m_tempo == menor_tempo)

# Mostrando o resultado
print("O melhor tempo foi na {}ª volta do corredor {}.".format(id_menor_tempo[1][0], id_menor_tempo[0][0]))

O melhor tempo foi na 5ª volta do corredor 4.


In [ ]:
# Tempo médio
media = np.mean(m_tempo, axis=1)
print('Média de cada corredor = \n', media)

Média de cada corredor = 
 [107.6 107.7 116.4 134.7 104.1 114.8]


In [ ]:
# Classificação
classificacao = np.argsort(media)
print("Classificação dos corredores(1º lugar até 6º) = ", classificacao)

Classificação dos corredores =  [4 0 1 5 2 3]


### Exercício 4

Faça uma função que retorne o resultado de um jogo da velha. Essa função deverá receber uma matriz 3x3 que representa o tabuleiro do jogo. As casas que não foram preenchidas por nenhum jogador será representada pelo valor 0, as preenchidas pelo Jogador 1 será representada pelo valor 1 e para o Jogador 2, use -1.

Assim, as possíveis saídas do programa serão:

* Se alguma linha, coluna ou vertical for preenchida com o mesmo símbolo, você deverá informar que o jogo acabou e indicar o vencedor.
* Se ainda estiver casas faltando para serem preenchidas, é necessário informar que o jogo não foi finalizado.
* Se nenhuma das condições anteriores for satisfeita, seu programa deverá retornar que houve empate.

Exemplo: dada a seguinte matriz A
$$
A = \left[
\begin{array}{ccc}
-1 & 0 & 1 \\
-1 & 1 & -1 \\
1 & 0 & 0
\end{array}
\right]
$$

seu programa deve retornar "O jogo acabou. O vencedor é o jogador 1!"



In [ ]:
# Escreva sua solução aqui.