<a href="https://colab.research.google.com/github/BrunaSR/MinicursoPython/blob/main/Notebooks/ParteIV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Minicurso Python Parte IV

Esse notebook apresenta exemplos e exercícios sobre a biblioteca Numpy

# Como criar um array

In [ ]:
# Importação da biblioteca
import numpy as np

### Vetores

In [ ]:
# Criação de um vetor a partir de uma lista
vetor = np.array([1, 2, 3, 4, 5])

print("Meu primeiro array com numpy = ", vetor)
print(type(vetor))

Meu primeiro array com numpy =  [1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# Acesso aos elementos de um array unidimensional
print('O segundo elemento do meu vetor é = ', vetor[1])
print('Os 3 últimos elementos são = ', vetor[-3:])
print('O segundo terceiro e quarto elementos são = ', vetor[1:3])

O segundo elemento do meu vetor é =  2
Os 3 últimos elementos são =  [3 4 5]
O segundo terceiro e quarto elementos são =  [2 3]


In [ ]:
# Informações de um array
print("Shape = ", vetor.shape)
print("Dimensões = ", vetor.ndim)
print("Tipos de dados do vetor = ", vetor.dtype)

Shape =  (5,)
Dimensões =  1
Tipos de dados do vetor =  int64


### Matrizes

In [ ]:
# Criação de uma matriz a partir de uma lista de listas
matriz = np.array([[1,2], [3, 4]])

print("Minha matriz quadrada = \n", matriz)
print("Shape = ", matriz.shape)

Minha matriz quadrada = 
 [[1 2]
 [3 4]]
Shape =  (2, 2)


In [ ]:
# Acesso aos elementos de um array multidimensional
print('Primeira linha da matriz = ', matriz[0])
print('Primeiro elemento da primeira linha = ', matriz[0, 0])
print('Primeiro elemento da segunda linha = ', matriz[1, 0])

Primeira linha da matriz =  [1 2]
Primeiro elemento da primeira linha =  1
Primeiro elemento da segunda linha =  3


### Funções para criação de arrays

In [ ]:
# Matriz 3x4 vazia
vazia = np.empty((3, 4))
print(vazia)

[[4.66095604e-310 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.04082753e-047 4.96012452e-090 2.95881656e-032]
 [1.55075274e+184 4.66239379e-033 3.99910963e+252 1.46030983e-319]]


In [ ]:
# Vetor coluna com zeros
zeros = np.zeros((6, 1))
print(zeros)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [ ]:
# Vetor linha de valor 1
vetor_um = np.ones((1, 6))
print(vetor_um)

[[1. 1. 1. 1. 1. 1.]]


In [ ]:
# Vetor com valores igualmente espaçados dentro de um intervalo
vetor = np.linspace(0, 1, 15)
print(vetor)

[0.         0.07142857 0.14285714 0.21428571 0.28571429 0.35714286
 0.42857143 0.5        0.57142857 0.64285714 0.71428571 0.78571429
 0.85714286 0.92857143 1.        ]


In [ ]:
# Vetor com valores dentro de um intervalo com passo igual 2
pares = np.arange(2, 11, 2)
print('Pares de 1 a 10 = ', pares)

Pares de 1 a 10 =  [ 2  4  6  8 10]


### Variáveis aleatórias

In [ ]:
# Valores aleatórios de uma distribuição uniforme dentro do intervalo [0,1)
v = np.random.random(10)
print(v)

[0.51093677 0.88386357 0.96047983 0.98696519 0.63858842 0.83554216
 0.98273158 0.28953125 0.73679483 0.105234  ]


In [ ]:
# Valores aleatórios inteiros de uma distribuição uniforme dentro do intervalo [0,1)
v = np.random.randint(7)
print(v)

1


In [ ]:
# Valores aleatórios de uma distribuição normal padrão 
v = np.random.randn(2, 3)
print(v)

[[ 1.40974587  1.28016672 -0.5136921 ]
 [ 0.07090824 -0.23663137  0.01907614]]


### Operações com os arrays

In [ ]:
# Operações entre um número e uma array
matriz = np.array([[1, 2, 3], [4, 5, 6]])
num = 2

print('Soma = \n', matriz + num)
print('\nSubtração = \n', matriz - num)
print('\nDivisão = \n', matriz / num)
print('\nMultiplicação = \n', matriz * num)

Soma = 
 [[3 4 5]
 [6 7 8]]

Subtração = 
 [[-1  0  1]
 [ 2  3  4]]

Divisão = 
 [[0.5 1.  1.5]
 [2.  2.5 3. ]]

Multiplicação = 
 [[ 2  4  6]
 [ 8 10 12]]


In [ ]:
# Operações com matrizes
matriz1 = np.array([[2, 3], [1, 5]])
matriz2 = 4*np.ones((2, 2))

print('Matriz 1 = \n', matriz1)
print('\nMatriz 2 = \n', matriz2)

print('\nMultiplicação elemento por elemento de duas matrizes = \n', matriz1 * matriz2)
print('\nMultiplicação matricial = \n', matriz1 @ matriz2)
print('\nMultiplicação matricial = \n', matriz1.dot(matriz2))

Matriz 1 = 
 [[2 3]
 [1 5]]

Matriz 2 = 
 [[4. 4.]
 [4. 4.]]

Multiplicação entre os elemento por elemento de duas matrizes = 
 [[ 8. 12.]
 [ 4. 20.]]

Multiplicação matricial = 
 [[20. 20.]
 [24. 24.]]

Multiplicação matricial = 
 [[20. 20.]
 [24. 24.]]


### Funções importantes

In [ ]:
# Redimensionar um array
vetor = np.array([True, False, False, True, True, True])
matriz = vetor.reshape((3,2))

print("Array original = ", vetor)
print("Array modificado = \n", matriz)

Array original =  [ True False False  True  True  True]
Array modificado = 
 [[ True False]
 [False  True]
 [ True  True]]


In [ ]:
# Copiar um array
vetor1 = np.ones((1, 6))
print('Vetor 1 = ', vetor1)

vetor2 = vetor1[0, :3]
print('\nVetor 2 = ', vetor2)

# Modificando vetor 2
vetor2[0] = 5
print('\nVetor 2 modificado = ', vetor2)

# Verificando o vetor original
print('\nVerificando o vetor original = ', vetor1)

# Utilizando np.copy()
print('\n' + '-'*20 + 'Utilizando np.copy()' + '-'*20)
vetor3 = np.copy(vetor1[0, :3])
print('\nVetor 3 = ', vetor3)

vetor3[2] = 33
print("\nVetor 3 modificado = ", vetor3)

print("\nVerificando o vetor original = ", vetor1)

Vetor 1 =  [[1. 1. 1. 1. 1. 1.]]

Vetor 2 =  [1. 1. 1.]

Vetor 2 modificado =  [5. 1. 1.]

Verificando o vetor original =  [[5. 1. 1. 1. 1. 1.]]

--------------------Utilizando np.copy()--------------------

Vetor 3 =  [5. 1. 1.]

Vetor 3 modificado =  [ 5.  1. 33.]

Verificando o vetor original =  [[5. 1. 1. 1. 1. 1.]]


In [ ]:
# Soma de elementos
matriz = np.array([[1, 2, 3], [4, 5, 6]])

print('Soma das colunas = ', np.sum(matriz, axis=0))
print('Soma das linhas = ', np.sum(matriz, axis=1))
print('Soma de todos os elementos = ', np.sum(matriz))

Soma das colunas =  [5 7 9]
Soma das linhas =  [ 6 15]
Soma de todos os elementos =  21


In [ ]:
# Algumas estatísticas

print('Desvio padrão = ', np.std(matriz))
print('Média = ', np.mean(matriz))
print('Variância = ', np.var(matriz))

Desvio padrão =  1.707825127659933
Média =  3.5
Variância =  2.9166666666666665


# Exercícios

### Exercício 1

Crie um array de inteiros de 32 bits de formato (4, 5, 3), onde todos os elementos são iguais a 7.


In [ ]:
# Escreva sua solução aqui.

### Exercício 2
Faça uma função que dado um intervalo fechado [a, b] e um número de pontos n, retorne o vetor x formado pelos n pontos obtidos a partir do intervalo, e o vetor y cujo i-ésimo elemento é dado por 

> $y_i = x_i^2 + 5$.




In [ ]:
# Escreva sua solução aqui.

### Exercício 3
Uma pista de Kart permite 10 voltas para cada um de 6 corredores. Uma matriz com os tempos (em segundos) de cada volta de cada corredor é dada. Com essa matriz, seu programa deve informar:
 - De quem foi a melhor volta da prova, e em que volta.
 - Classificação final em ordem crescente.
 - Qual foi a volta com a média mais rápida.

In [ ]:
# Escreva sua solução aqui.

### Exercício 4

Faça uma função que retorne o resultado de um jogo da velha. Essa função deverá receber uma matriz 3x3 que representa o tabuleiro do jogo. As casas que não foram preenchidas por nenhum jogador será representada pelo valor 0, as preenchidas pelo Jogador 1 será representada pelo valor 1 e para o Jogador 2, use -1.

Assim, as possíveis saídas do programa serão:

* Se alguma linha, coluna ou vertical for preenchida com o mesmo símbolo, você deverá informar que o jogo acabou e indicar o vencedor.
* Se ainda estiver casas faltando para serem preenchidas, é necessário informar que o jogo não foi finalizado.
* Se nenhuma das condições anteriores for satisfeita, seu programa deverá retornar que houve empate.

Exemplo: dada a seguinte matriz A
$$
A = \left[
\begin{array}{ccc}
-1 & 0 & 1 \\
-1 & 1 & -1 \\
1 & 0 & 0
\end{array}
\right]
$$

seu programa deve retornar "O jogo acabou. O vencedor é o jogador 1!"



In [ ]:
# Escreva sua solução aqui.